"""
publish_only.py
Publishes a pre-built HTML report (received from Grafana AI automation via
GitHub repository_dispatch) directly to Confluence — no Grafana querying needed.

Environment variables required:
  REPORT_TITLE  — Confluence page title
  REPORT_HTML   — Full HTML body of the report (generated by Grafana AI)
  + all CONFLUENCE_* secrets
"""

import sys
import os
from pathlib import Path

try:
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
except ImportError:
    pass

REQUIRED = [
    "CONFLUENCE_BASE_URL",
    "CONFLUENCE_EMAIL",
    "CONFLUENCE_API_TOKEN",
    "CONFLUENCE_SPACE_KEY",
    "CONFLUENCE_PARENT_PAGE_ID",
    "REPORT_TITLE",
    "REPORT_HTML",
]

missing = [v for v in REQUIRED if not os.environ.get(v)]
if missing:
    print(f"[ERROR] Missing required environment variables: {', '.join(missing)}")
    sys.exit(1)

from confluence_publisher import ConfluencePublisher


def main():
    title = os.environ["REPORT_TITLE"]
    html_body = os.environ["REPORT_HTML"]

    print(f"\n{'=' * 65}")
    print(f"  Grafana AI Report → Confluence Publisher")
    print(f"  Title : {title}")
    print(f"  HTML  : {len(html_body):,} characters")
    print(f"{'=' * 65}\n")

    publisher = ConfluencePublisher()
    result = publisher.publish(title, html_body)

    page_id = result.get("id", "N/A")
    webui = result.get("_links", {}).get("webui", "")
    base = os.environ.get("CONFLUENCE_BASE_URL", "").rstrip("/")
    if base.endswith("/wiki"):
        base = base[:-5]
    full_url = f"{base}{webui}" if webui else "N/A"

    print(f"\n{'=' * 65}")
    print(f"  Report published successfully!")
    print(f"  Page ID : {page_id}")
    print(f"  URL     : {full_url}")
    print(f"{'=' * 65}\n")


if __name__ == "__main__":
    main()
